server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

zuul:
  routes:
    order-service: /order/**
    product-service: /product/**
  ignored-patterns: /*-service/**
